ALTER TABLE sessions ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'study';
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS linked_test_id TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS linked_test_type TEXT
